
services:
  # 1) Postgres Database
  db:
    image: postgres:15
    container_name: mvp_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mvp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"   # Expose DB port for local dev (optional)
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2) FastAPI Application
  backend:
    build: ./backend
    container_name: mvp_api
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: mvp_db
      DB_USER: postgres
      DB_PASSWORD: secret
    ports:
      - "8000:8000"   # Host port : Container port
    # If you need environment variables for summarization or others, add them here.

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
